### ISSUE TITLE
Not a json object

### ISSUE THREAD

**Issue by border999** [Teddy0008/ad_extendra#2]
![image](https://github.com/Teddy0008/ad_extendra/assets/11824584/e1587fa4-42e9-4751-9559-83d5b2a9cfbf)

**Comment by itsmeteddyhere** [comment]
First, are you sure you have the correct Minecraft version and Ad Astra version? The mod currently supports only one specific Ad Astra version.

**Comment by border999** [comment]
ad_astra-forge-1.20.1-1.15.18
ad_extendra-0.1.1

**Comment by itsmeteddyhere** [comment]
Yeah you actually need ad_astra-forge-1.20.1-1.15.5 otherwise it won't work
